### ISSUE TITLE
images in articles not perfectly centered

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#106]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to this project or any open source software (OSS) in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aopenelements+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution.

## 👾 Description of the issue

By using the centered image tag the image is not correctly centered at all places.
An example can be found in this blog post: https://open-elements.com/posts/2023/02/07/best-practices-and-anti-pattern-for-logging-in-java-and-other-languages/

In the post you can find the following image that is not perfectly layouted as a centered elements acording to the text:
<img width="753" alt="Bildschirmfoto 2024-07-06 um 14 05 09" src="https://github.com/OpenElements/open-elements-website/assets/9443847/2e8b1510-ea6d-406f-8fa0-d25cefa9db2d">

In the markdown article file the image is defined like this:

`{{< centered-image src="/posts/2023-02-07-logging-in-java-and-other-languages/logging-level-scale.jpg" width="100%" showCaption="true" alt="Logging level scale">}}`

The source of the post can be found here: https://github.com/OpenElements/open-elements-website/blob/main/content/posts/2023-02-07-logging-in-java-and-other-languages.md

For the centered image a [Hugo](https://gohugo.io) shortcode is used that can be found here: https://github.com/OpenElements/open-elements-website/blob/main/layouts/shortcodes/centered-image.html

To solve this issue the shortcode should be fixed in a way that the image is always shown centered.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button)
- [ ] **Check out the forked repository** on your local machine
- [ ] **Create a feature branch** for the issue
- [ ] **Solve the issue** in your branch
- [ ] **Commit your changes:** to your branch
- [ ] **Start a Pull Request (PR)**: in our repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error, do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will discuss it with you and describe the next steps for solving it.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

**Comment by Atharva1723** [comment]
Can I work on this issue?
