### ISSUE TITLE
Preview images of post should provide link on click

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#109]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to this project or any open source software (OSS) in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aopenelements+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution.

## 👾 Description of the issue

The website contains a blog that is not shown in the main menu today since the work on the blog feature still needs to be fully done. Anyway, the blog is already part of the page and can be found here: https://open-elements.com/posts/

On that page, you see a list of blog post previews. To show the blog post, you need to click on the text of the blog. When clicking on the preview image of a post, nothing happens. Here, we want to have the full blog post preview as a link to the post. So, when clicking on the preview image of a post, the user should be forwarded to the blog post.

<img width="1200" alt="Bildschirmfoto 2024-07-20 um 16 05 57" src="https://github.com/user-attachments/assets/a22b3573-c0f1-44e8-8e4e-1778706f0048">

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button)
- [ ] **Check out the forked repository** on your local machine
- [ ] **Create a feature branch** for the issue
- [ ] **Solve the issue** in your branch
- [ ] **Commit your changes:** to your branch
- [ ] **Start a Pull Request (PR)**: in our repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error, do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will discuss it with you and describe the next steps for solving it.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

**Comment by shbhmexe** [comment]
hey assign me this issue ,, i want to solve this and have potential skils to solve this

**Comment by hendrikebbers** [comment]
@shbhmexe sorry for the delay. Are you still interested in working on the issue?

**Comment by Goutamchoudhary907** [comment]
Hey @hendrikebbers I want to work on this plz assign me this

**Comment by Goutamchoudhary907** [comment]
Hey @hendrikebbers  i am unable to clone the repo it shows this error 
![Screenshot 2024-10-27 091954](https://github.com/user-attachments/assets/07c01652-6b56-4752-9ae9-31731a4b39f8)
I try multiple time and also try using SSH but this doesnt work

**Comment by Goutamchoudhary907** [comment]
Hey @hendrikebbers  Where is your Public folder in which index.html file is present i am unable to find index file which is located in public folder

**Comment by hendrikebbers** [comment]
YOu can find it here: https://github.com/OpenElements/open-elements-website/blob/main/layouts/index.html

The website is based on Hugo (https://gohugo.io) and you need to use hugo to build it

**Comment by Goutamchoudhary907** [comment]
This is not the mian file of page . Where is main index.html of website ?
Previously i see this in public folder but now there is no public filder in code

**Comment by Goutamchoudhary907** [comment]
Hey @hendrikebbers can you help today is last date of hacktober fest
