### ISSUE TITLE
Corners of blog previews not rounded

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#110]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to this project or any open source software (OSS) in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aopenelements+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution.

## 👾 Description of the issue

The website contains a blog that is not shown in the main menu today since the work on the blog feature still needs to be fully done. Anyway, the blog is already part of the page and can be found here: https://open-elements.com/posts/

On that page, you see a list of blog post previews. Here, the corners of the preview blocks should be rounded. Today, only the right side is rounded:

<img width="1317" alt="Bildschirmfoto 2024-07-20 um 16 15 31" src="https://github.com/user-attachments/assets/57770696-fa16-4fd9-8a67-ca25a746b465">

All corners of the block should be rounded in the same way.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button)
- [ ] **Check out the forked repository** on your local machine
- [ ] **Create a feature branch** for the issue
- [ ] **Solve the issue** in your branch
- [ ] **Commit your changes:** to your branch
- [ ] **Start a Pull Request (PR)**: in our repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error, do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will discuss it with you and describe the next steps for solving it.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

**Comment by MadhurSaluja** [comment]
Hi This is my first time contributing to an open-source Project for Hacktoberfest. I would really like to takeover this issue if it has not been corrected already. @hendrikebbers

**Comment by MadhurSaluja** [comment]
Hi @hendrikebbers I have created a PR to resolve the issue can you please have a look and let me know if any changed are required. Thanks :)
