### ISSUE TITLE
Link from German "About us" page to page for "Hendrik Ebbers" switches language to English

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#114]
By switching the page to German (DE) (1) and going on the "About us" ("Über uns") page you will find a link to "Hendrik Ebbers" in the first paragraph. Clicking on that link will switch the page to English (EN). The page should stay in German language.

<img width="1056" alt="desc" src="https://github.com/user-attachments/assets/6472b5cb-52cb-4be9-b288-88027e8c9c05">

Link to German "About us" / "Über uns" page: https://open-elements.com/de/about/

**Comment by dhvani2510** [comment]
I have found the fix for the issue
Fix the href in the file "content/about/index.de.md" to redirect to "/de/about-hendrik.html"  instead of just "/about-hendrik.html"

**Comment by hendrikebbers** [comment]
fixed by https://github.com/OpenElements/open-elements-website/pull/115#pullrequestreview-2347255267
