### ISSUE TITLE
Add Hiero to engagements section

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#116]
Hiero (https://hiero.org) should be added to engagements at https://open-elements.com/about/

**Comment by nooras** [comment]
Hey @hendrikebbers 
Is it open to work on ? Shall I add description as per my understanding?

**Comment by Ndacyayisenga-droid** [comment]
@hendrikebbers as we add Hiero (https://hiero.org/), I think we should get rid of Hedera and Hashgraph from **_Our Customers & Partners_**  section

**Comment by Ndacyayisenga-droid** [comment]
> Hey @hendrikebbers Is it open to work on ? Shall I add description as per my understanding?

@nooras you can do anything in a PR, @hendrikebbers will provide a clear text when he gets less busy
