### ISSUE TITLE
Add orcwg to engagements section

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#118]
We need to add the OPEN REGULATORY COMPLIANCE WORKING GROUP (https://orcwg.org) to the engagements section.

**Comment by hendrikebbers** [comment]
ORC WG logo
![Uploading ORC_Logo-Horz-Full_Color-CMYK .svg…]()

**Comment by Ndacyayisenga-droid** [comment]
@rdodiya you can open a draft PR with this, @hendrikebbers will provide the text when he gets less busy

**Comment by rdodiya** [comment]
Hi @Ndacyayisenga-droid , Please review and merge the PR #125
