### ISSUE TITLE
Change hover link of OTH Regensburg logo

### ISSUE THREAD

**Issue by nooras** [OpenElements/open-elements-website#120]
## 🆕🐥 First Timers Only
This issue is reserved for people who have never contributed to this project or any open source software (OSS) in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by ['good first issue'](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Aopenelements+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution.

## 👾 Description of the issue
Currently on hover over OTH Regensburg logo it shows some other Partner url (SwirldsLabs).
![Untitled design (3)](https://github.com/user-attachments/assets/62d36869-d568-4e91-a5d5-22054c8d6261)

**Comment by rdodiya** [comment]
Hi, @nooras , I would like to contribute to the open-elements-website. Could you please assign this task to me?

**Comment by nooras** [comment]
Hey @rdodiya 
One u raise a PR and it got merged then it will automatically become a part of Hacktoberfest 24

**Comment by hendrikebbers** [comment]
https://github.com/OpenElements/open-elements-website/pull/122
