### ISSUE TITLE
Background image (arrows are hidden on posts page)

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#128]
Currently some arrows in the background are partly hidden by the post previews. That looks broken and should be changed.

<img width="1339" alt="Bildschirmfoto 2024-11-24 um 12 25 59" src="https://github.com/user-attachments/assets/cf4095da-7634-4523-b00a-68d9885695af">

**Comment by Lemeri123** [comment]
Hello @hendrikebbers I would like to work on this issue but I cant seem to navigate to the post page through the home page. could please help me out
