### ISSUE TITLE
Layout for "Ask Maven" app

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/open-elements-website#94]
We need the following pages: https://www.figma.com/proto/uNorvr0G3GjpeUruOTOGwk/Open-elements_design?page-id=856%3A5062&node-id=856-5063&viewport=553%2C339%2C0.13&t=kofaFnr7sEmu1CrC-1&scaling=min-zoom

<img width="1429" alt="Bildschirmfoto 2024-06-04 um 18 14 42" src="https://github.com/OpenElements/open-elements-website/assets/9443847/c4a8a52b-ffb3-4acb-a0a7-a9d24e1d6f64">

**Comment by Subtain-Farooq** [comment]
Please share the Figma file or share the Figma link.
